services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: biblioteca
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      ConnectionStrings__Default: "Host=db;Port=5432;Username=postgres;Password=postgres;Database=biblioteca;SSL Mode=Disable;Trust Server Certificate=true"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "8080:8080"

volumes:
  dbdata:
