services:
  db:
    image: postgres:16
    container_name: biblioteca-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: biblioteca
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d biblioteca"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
